Fix installation with pip >= 10
pip.req was moved to the internal namespace.
Installing with newer pip version fails with:

  ModuleNotFoundError: No module named 'pip.req